name: inception

# ---------------------- SERVICES -----------------------
services:
# ======================= NGINX =======================
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      wordpress:
        condition: service-started
    depends_on:
      - 
    restart: always
  
# ====================== MARIADB ======================
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - inception_network
    volumes:
      - wordpress_db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot -p$(cat /run/secrets/db_root_password) -e 'SELECT 1';"] 
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

# ====================== WORDPRESS ======================
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 9000
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception_network
    volumes:
      - wordpress_files:/app #################################
    restart: always

# ---------------------- NETWORKS -----------------------

networks:
  inception_network: 
    driver: bridge

# ---------------------- VOLUMES ------------------------

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jguelen/data/wordpress_db 
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jguelen/data/wordpress_files

# ---------------------- SECRETS ------------------------

secrets:
  db_password:
    file: secrets/db_password
  db_root_password:
    file: secrets/db_root_password
  wp_password:
    file: secrets/wp_password