# Example config file /etc/vsftpd/vsftpd.conf
#
# The default compiled in settings are fairly paranoid. This sample file
# loosens things up a bit, to make the ftp daemon more usable.
# Please see vsftpd.conf.5 for all compiled in defaults.
#
anonymous_enable=NO
#
local_enable=YES

# White List Pattern
userlist_deny=NO
userlist_enable=YES
userlist_file=/etc/vsftpd/user_list

write_enable=YES
local_umask=022
dirmessage_enable=YES
#xferlog_std_format=YES
# Enable this and the server will recognise asynchronous ABOR requests. Not
# recommended for security (the code is non-trivial). Not enabling it,
# however, may confuse older FTP clients.
#async_abor_enable=YES
#
ftpd_banner="Welcome to Inception's FTP service."
chroot_local_user=YES
listen=YES
listen_ipv6=NO

pam_service_name=vsftpd
tcp_wrappers=YES

rsa_cert_file=/etc/ssl/private/vsftpd.pem
rsa_private_key_file=/etc/ssl/private/vsftpd.pem

ssl_enable=YES
allow_anon_ssl=NO
force_local_data_ssl=YES
force_local_logins_ssl=YES

ssl_tlsv1=NO
ssl_sslv2=NO
ssl_sslv3=NO

require_ssl_reuse=NO

pasv_address=jguelen.42.fr
pasv_addr_resolve=YES


pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
port_enable=YES
# ref: https://www.benscobie.com/fixing-500-oops-vsftpd-refusing-to-run-with-writable-root-inside-chroot/
allow_writeable_chroot=YES

# For all the segfaults
#seccomp_sandbox=NO
#isolate_network=NO
#session_support=NO
#xferlog_enable=NO
#no_log_lock=YES
#syslog_enable=NO
#setproctitle_enable=NO
#background=NO
ssl_ciphers=HIGH

#debug_ssl=YES